# Generated by Django 4.0.4 on 2022-05-30 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='player',
        ),
    ]
