# Generated by Django 4.0.4 on 2022-05-27 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Great_Number', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player_score',
            old_name='user',
            new_name='player_id',
        ),
        migrations.RenameField(
            model_name='player_score',
            old_name='user_score',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='player',
            name='user_name',
        ),
        migrations.AddField(
            model_name='player',
            name='player_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
